os:
  - linux
language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run pytest --pep8 --cov=./
after_success:
  - pipenv run codecov